### ISSUE TITLE
ImportError: libXrender.so.1

### ISSUE THREAD

**Issue by schelhorn** [IBM/dl-interpretability-compbio#9]
Hi there,

I have pulled the pre-build image from docker hub as well as (as an alternative) rebuilt an image directly from this repository; in both cases, when accessing the Jupiter Notebook server in the container and running the first cell of the `paccmann.ipynb`, I get the following error (on Docker for Mac 2.0.5/macOS Mojave, latest Docker and macOS releases, without experimental Docker features):

```python
ImportError                               Traceback (most recent call last)
<ipython-input-1-0b1b62746cd1> in <module>
      1 # import all the needed libraries
      2 import pandas as pd
----> 3 from depiction.models.paccmann import PaccMannSmiles, PaccMannCellLine

/opt/conda/lib/python3.7/site-packages/depiction/models/paccmann/__init__.py in <module>
      1 """PaccMann initialization."""
----> 2 from .core import (
      3     PaccMannCellLine, PaccMannSmiles
      4 )

/opt/conda/lib/python3.7/site-packages/depiction/models/paccmann/core.py in <module>
      6 import tensorflow as tf
      7 from paccmann.models import paccmann_model_fn, MODEL_SPECIFICATION_FACTORY
----> 8 from .smiles import process_smiles, get_smiles_language
      9 from ..core import TextModel, get_model_file
     10 from ...core import Task

/opt/conda/lib/python3.7/site-packages/depiction/models/paccmann/smiles.py in <module>
      7 import matplotlib.cm as cm
      8 from operator import itemgetter
----> 9 from rdkit import Chem
     10 from rdkit.Chem.Draw import rdMolDraw2D
     11 from spacy.vocab import Vocab

/opt/conda/lib/python3.7/site-packages/rdkit/Chem/__init__.py in <module>
     22 from rdkit.Chem.rdchem import *
     23 from rdkit.Chem.rdmolfiles import *
---> 24 from rdkit.Chem.rdmolops import *
     25 from rdkit.Chem.inchi import *
     26 try:

ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
```

Is there a `sudo apt-get install libxrender1` missing from the Dockerfile, perhaps? (haven't tested since you nuked `/var/lib/apt/lists/*` in the image)

**Comment by drugilsberg** [comment]
Hey @schelhorn many thanks for notifying us. This is related to the temporary lack of test #8 as you noticed :).

**Comment by drugilsberg** [comment]
Should be addressed in PR #10. The CI cycle has already updated the image on Docker Hub.

**Comment by schelhorn** [comment]
Fixed, closing. However, I noticed that the fixed notebook downloads 300 megs from box.com servers. Not sure how that scales with 100 people at ISMB doing that simultaniously over conference Wifi.

**Comment by drugilsberg** [comment]
Good point, will consider including all the models directly in the image. Thanks again for the bug report.
